### ISSUE TITLE
TS-Warp Unable to start failing with the below error. 

### ISSUE THREAD

**Issue by akshaybagewadi** [mezantrop/ts-warp#4]
Stopping ts-warp with force: zsh: killed     sudo /usr/local/etc/ts-warp.sh stop -f
akshay@Akshay's MacBook etc % 
akshay@Akshay's MacBook etc % sudo /usr/local/etc/ts-warp.sh start -f
Starting ts-warp: pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
done
akshay@Akshay's MacBook etc % sudo /usr/local/etc/ts-warp.sh status  
ts-warp is not running: done
akshay@Akshay's MacBook etc %

**Comment by mezantrop** [comment]
Userlevel issue when filling in the configuration files.
