### ISSUE TITLE
Man page is not compatible with mandoc(1) on MacOS

### ISSUE THREAD

**Issue by esmiralha** [mezantrop/ts-warp#5]
typing `man` at the root of the project issues a warning and displays an unformatted man page.

**Comment by esmiralha** [comment]
btw, thank you for the project!

**Comment by mezantrop** [comment]
Thank you for discovering the issue. Saying the truth, ts-warp manpages are still incomplete, beware of that. Though, I have checked all the files like: `mandoc -l  ts-warp.5 `and it shows normal formatted output with highlights on macOS and FreeBSD, so everything should be OK, check your system for that.

Also, `mandoc -T lint ts-warp.5` returns various non-critical messages for all the pages:

```
mandoc -T lint ts-warp.5
mandoc: ts-warp.5:23:120: STYLE: whitespace at end of input line
mandoc: ts-warp.5:27:115: STYLE: whitespace at end of input line
mandoc: ts-warp.5:60:37: STYLE: whitespace at end of input line
mandoc: ts-warp.5:19:5: STYLE: lower case character in document title: TH ts\-warp5
mandoc: ts-warp.5:19:17: WARNING: missing date, using "": TH
mandoc: ts-warp.5:94:2: WARNING: skipping paragraph macro: PP empty
mandoc: ts-warp.5:77:2: WARNING: skipping paragraph macro: PP after SH
```

Will fix this eventually, when I complete documenting ts-warp.

**Comment by mezantrop** [comment]
> btw, thank you for the project!

You are more than welcome :)

**Comment by mezantrop** [comment]
Also the project is open for changes, accepting pull requests with a great pleasure.

**Comment by mezantrop** [comment]
mandoc issues fixed: https://github.com/mezantrop/ts-warp/commit/beeb60888ee6db60ba70d81c87fc8a5dd2fbc090 
Thanks again :)
