### ISSUE TITLE
Added to nixpkgs

### ISSUE THREAD

**Issue by heywoodlh** [mezantrop/ts-warp#9]
This isn't an issue, but a notification I've added ts-warp to nixpkgs to easily install with the Nix package manager. Here's the corresponding Pull Request: https://github.com/NixOS/nixpkgs/pull/334469

Please let me know if this is an issue or if there are any questions/concerns -- I will close this.

**Comment by mezantrop** [comment]
Thank you very much @heywoodlh. Appreciate it a lot!
